### ISSUE TITLE
Please add option to embed cover art from folder

### ISSUE THREAD

**Issue by Emasoft** [odrusso/chapterify#4]
Please add option to embed cover art from folder. Usually in the audiobook folder the cover image is named "Cover.jpg" or "<name_of_audiobook_file>.jpg". The format is jpg, jpeg or png.

**Comment by odrusso** [comment]
#5 
@Emasoft - can you verify this works for you before I merge into `master`

**Comment by Emasoft** [comment]
ok, I'll check now!

**Comment by Emasoft** [comment]
> #5
> @Emasoft - can you verify this works for you before I merge into `master`

It gives me this error:
```
[~chapterize]$ chapterize.py "Divine Arsenal Vol_1 Audiobook.m4b" "./Dual/*.m4b" --cover_image "./Dua
l/Divine Arsenal Dual Weapon Cultivation Divine Arsenal, Book 1.jpg" --keep_chapter_names

mktemp: command not found
Traceback (most recent call last):
  File "/Documents/chapterize/chapterize.py", line 146, in <module>
    new_metadata_file = open(new_metadata_file_location, 'w')
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: ''
```

I don't have mktemp on my system. Can you replace it with something else?
For example:  https://github.com/Parquery/temppathlib

**Comment by odrusso** [comment]
@Emasoft PR to remove mktmp, #6

**Comment by odrusso** [comment]
@Emasoft This has all been merged to main. Will close this off, feel free to raise another issue if you have any other feature requests, or have any other problems.
